# -*- coding: utf-8 -*-
"""Capstone_PembangunanModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOzZ4SkXWps5EcXjnx5ei5qmMf-FbE0t

## **1. Import Library**
"""

# Pastiin ini dijalanin dulu ya
#!pip install scikit-learn-extra
#!pip install "numpy<2"

# Library
import pandas as pd
import numpy as np
import joblib
import os

# Optional plotting and extra libs. If missing, continue with warnings or fallbacks.
try:
    import seaborn as sns
    import matplotlib.pyplot as plt
    PLOTTING_AVAILABLE = True
except Exception:
    sns = None
    plt = None
    PLOTTING_AVAILABLE = False
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
try:
    from sklearn_extra.cluster import KMedoids
    KM_USE = 'kmedoids'
except Exception:
    # fallback to KMeans when sklearn_extra is not available
    from sklearn.cluster import KMeans as KMedoids
    KM_USE = 'kmeans_fallback'
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
try:
    from yellowbrick.cluster import KElbowVisualizer
    YB_AVAILABLE = True
except Exception:
    KElbowVisualizer = None
    YB_AVAILABLE = False
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report

# If running in Google Colab, manually mount Drive before using Colab paths:
# from google.colab import drive
# drive.mount('/content/drive')

"""## **2. Memuat Dataset**"""

# Load dataset hasil processing
url = "https://drive.google.com/uc?id=15xk83k4FAHyJAjnK4eqTpyn6N9dHtyxZ"
data = pd.read_csv(url)

#Hapus kolom year_month
data = data.drop('year_month', axis=1)

# Tampilkan data
data.head()

"""## **3. Membangun Model**

1. Model Clustering (K-Medoids)
"""

# Melakukan visualisasi Elbow Method menggunakan KElbowVisualizer()

# Elbow Method untuk K-Medoids
# k_range = range(2, 10)
# silhouette_scores = []
'''
for k in k_range:
    kmedoids = KMedoids(n_clusters=k, random_state=42)
    kmedoids.fit(data)
    score = silhouette_score(data, kmedoids.labels_)
    silhouette_scores.append(score)

plt.figure(figsize=(8, 4))
plt.plot(k_range, silhouette_scores, marker='o')
plt.title('Silhouette Score vs Jumlah Cluster (K-Medoids)')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('Silhouette Score')
plt.xticks(k_range)
plt.grid(True)
plt.show()

best_k = k_range[silhouette_scores.index(max(silhouette_scores))]
print(f"Jumlah cluster terbaik: {best_k}")
'''

# Buat dan latih model K-Medoids
model_kmedoids = KMedoids(n_clusters=2, random_state=42)
model_kmedoids.fit(data)

# Menghitung dan menampilkan nilai Silhouette Score.

# Dapatkan hasil (label) cluster dari model 'kmedoids' yang telah di-fit
labels = model_kmedoids.labels_

# Panggil fungsi untuk menghitung silhouette score
# score = silhouette_score(data, labels)

# Cetak skornya
# print("Silhouette Score:", score)

# Simpan Model K-Means (or KMeans fallback)
BASE_DIR = os.path.dirname(__file__)
joblib.dump(model_kmedoids, os.path.join(BASE_DIR, 'model_kmedoids.pkl'))

data['Cluster'] = labels

numerical_cols = data.select_dtypes(include=['number']).columns
agg_summary = data.groupby('Cluster')[numerical_cols].agg(['mean', 'min', 'max']).round(2).T

# Notebook-specific display() is not available in plain Python; print a summary instead.
try:
    print(agg_summary.to_string())
except Exception:
    print(agg_summary)

# Save data hasil clustering
df_cluster = data.copy()

df_cluster

# Simpan data hasil clustering
df_cluster.to_csv(os.path.join(BASE_DIR, 'Financial_Transactions_Cluster.csv'), index=False)

# Grafik Korelasi Fitur
corr_matrix = df_cluster.corr()
if PLOTTING_AVAILABLE:
    try:
        plt.figure(figsize=(10, 8))
        sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
        plt.title('Korelasi Fitur')
        plt.show()
    except Exception:
        print('Plotting failed or not supported in this environment; skipping plot.')
else:
    print('seaborn/matplotlib not available; skipping correlation heatmap.')

"""2. Model Klasifikasi"""

# Menggunakan train_test_split() untuk melakukan pembagian dataset
X = df_cluster.drop('Cluster', axis=1)
y = df_cluster['Cluster']


# Panggil fungsi untuk membagi data.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

### SELESAI CODE ###

print("Jumlah data total: ",len(X))
print("Jumlah data latih: ",len(X_train))
print("Jumlah data test: ",len(X_test))

# Latih Model decision tree
decision_tree_model = DecisionTreeClassifier(random_state=42)

# 2. Latih (fit) model dengan data training (X_train dan y_train)
decision_tree_model.fit(X_train, y_train)

# Menyimpan Model
joblib.dump(decision_tree_model, os.path.join(BASE_DIR, 'decision_tree_model.pkl'))

"""## 4. Evaluasi Akurasi dan Tuning Model"""

# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

# Buat prediksi pada data 'X_test'
y_pred_dt = decision_tree_model.predict(X_test)

# Tampilkan classification_report
print("Decision Tree Performance")
print(classification_report(y_test, y_pred_dt))

# Lakukan Hyperparameter Tuning dan Latih ulang

# Tentukan Hyperparameter yang akan di-tuning
params = {
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy']
}

# Buat objek GridSearchCV
new_model_tuned = GridSearchCV(
    estimator = DecisionTreeClassifier(random_state=42),
    param_grid = params,
    cv = 5,
    scoring = 'accuracy'
)

# Latih model
new_model_tuned.fit(X_train, y_train)

# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

# Buat prediksi pada 'X_test' Gunakan model yang sudah di-tuning
y_pred_tuning = new_model_tuned.predict(X_test)

# Tampilkan classification_report untuk model yang sudah di-tuning
print("Tuned Model Performance")
print(classification_report(y_test, y_pred_tuning))

y_pred_all = decision_tree_model.predict(X)

df_klasifikasi = df_cluster.copy()
df_klasifikasi['Cluster_Pred'] = y_pred_all

df_klasifikasi['Cluster_Pred']

# Simpan data hasil klasifikasi
df_klasifikasi.to_csv(os.path.join(BASE_DIR, 'Financial_Transactions_Klasifikasi.csv'), index=False)
