# -*- coding: utf-8 -*-
"""Capstone_DataProcessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOAjynIrCXsaALlqDj06MqplK5XiM6kt

## **1. Import Library**
"""

# Library
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

"""## **2. Memuat Dataset**"""

# Load dataset
url = "https://drive.google.com/uc?id=1D0Zb-4LztkoTAEePhXUazXIdctoHfFmR"
df = pd.read_csv(url)

df.head()

# Informasi Dataset
print("Informasi Dataset : ")
df.info()

df.describe()

"""## **3. Preprocessing Data**"""

# Hapus data kurang berguna
drop_cols = [
    'id', 'title', 'currency',
    'transfer-amount', 'transfer-currency',
    'to-account', 'receive-amount', 'receive-currency',
    'description', 'due-date'
]
df = df.drop(columns=drop_cols)

df.head()

# Konversi amount ke numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Missing Value
print("Missing Value : ")
df.isnull().sum()

# Penanganan Missing Value
df['category'] = df['category'].fillna(df['category'].mode()[0])
df['amount'] = df['amount'].fillna(df['amount'].median())

df.isnull().sum()

# Data Duplikat
print("Data Duplikat : ")
df.duplicated().sum()

# Modifikasi amount
df['amount'] = df['amount'] * 1000
df.head()

#Outlier
df.boxplot(column='amount', by='type', figsize=(8, 5))
plt.title('Boxplot Amount per Tipe Transaksi')
plt.suptitle('')
plt.ylabel('Amount')
plt.show()

# Pecah Kolom Date
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['year_month'] = df['Date'].dt.to_period('M').astype(str)
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day

df=df.drop(columns='Date')

df.head()

# Validasi Informasi Dataset
print("Informasi Dataset : ")
df.info()

df.describe()

df.to_csv('Financial_Transactions.csv', index=False)

"""## **4. Exploratory Data Analysis (EDA)**

Pertanyaan Bisnis
1. Bagaimana tren pengeluaran per bulan?
2. Apa kategori pengeluaran tertinggi dan terendah di setiap bulan?
3. Apakah ada kategori pengeluaran yang tergolong melampaui batas normal di tiap bulannya?
4. Apa kategori pengeluaran yang sering dilakukan tiap bulannya?

note: mencari karakteristik data >> eda
eda untuk mempelajari hubungan feature satu dengan feature lainnya.
"""

# mencari tahu jumlah baris dan kolom
df.shape

# Statistik deskriptif
df.describe()

# menampilkan histogram untuk kolom numerik amount dan melihat distribusi data amount
sns.histplot(df['amount'], kde=True)

# Amount vs category
sns.barplot(x='category', y='amount', data=df, errorbar=None)
plt.title('Rata-Rata Pengeluaran & Pemasukan vs Kategory')
plt.xlabel('Kategory')
plt.ylabel('Rata-Rata Pengeluaran')
plt.show()

# Fluktuasi pengeluaran tiap bulannya
df['year_month'] = df['year'].astype(str) + '-' + df['month'].astype(str).str.zfill(2)

df_plot = df[
    (df['year'] >= 2023) &
    (df['year'] <= 2024) &
    (df['type'] == 'EXPENSE')
].copy()

df_plot = df_plot.sort_values(by='year_month')

order_year_month = df_plot['year_month'].unique()

plt.figure(figsize=(15, 6))
sns.barplot(
    x='year_month',
    y='amount',
    data=df_plot,
    estimator='mean',
    errorbar=None,
    order=order_year_month
)

plt.title('Rata-Rata Pengeluaran per Bulan (2023-2024)')
plt.xlabel('Tahun-Bulan')
plt.ylabel('Rata-Rata Pengeluaran')
plt.xticks(rotation=45)
plt.show()

# Amount vs account
sns.barplot(x='account', y='amount', data=df, errorbar=None)
plt.title('Rata-Rata amount vs account')
plt.xlabel('account')
plt.ylabel('Rata-Rata amount')
plt.show()

# Amount vs Type
sns.barplot(x='type', y='amount', data=df, errorbar=None)
plt.title('Rata-Rata amount vs type')
plt.xlabel('type')
plt.ylabel('Rata-Rata amount')
plt.show()

"""MENJAWAB PERTANYAAN BISNIS"""

# Bagaimana tren pengeluaran per bulan pada tahun 2023 dan 2024?
df['year_month'] = df['year'].astype(str) + '-' + df['month'].astype(str).str.zfill(2)

df_plot = df[(df['year'] >= 2023) & (df['year'] <= 2024) & (df['type'] == 0)].copy()
df_plot = df_plot.sort_values(by='year_month')

order_year_month = df_plot['year_month'].unique()

plt.figure(figsize=(15, 6))
sns.barplot(
    x='year_month',
    y='amount',
    data=df_plot,
    estimator='mean',
    errorbar=None,
    order=order_year_month
)

plt.title('Rata-Rata Pengeluaran per Bulan (2023-2024)')
plt.xlabel('Tahun-Bulan')
plt.ylabel('Rata-Rata Pengeluaran')
plt.xticks(rotation=45)
plt.show()

"""Pengeluaran tiap bulan memiliki tren naik dan tiap bulan cenderung berfluktuatif. pengeluaran terbesar terlihat pada bulan juni dan agustus tahun 2024"""

# Juni
kategori_pengeluaran_juni = df[
    (df['year_month'] == '2024-06') &
    (df['type'] == 'EXPENSE')
]

kategori_pengeluaran_juni = kategori_pengeluaran_juni.groupby('category')['amount'].mean().reset_index()
kategori_pengeluaran_juni = kategori_pengeluaran_juni.sort_values(by='amount', ascending=False)

tertinggi_juni = kategori_pengeluaran_juni.iloc[0]['category']
terendah_juni = kategori_pengeluaran_juni.iloc[-1]['category']

plt.figure(figsize=(10, 6))
plt.bar(kategori_pengeluaran_juni['category'], kategori_pengeluaran_juni['amount'])

plt.title('Rata-Rata Pengeluaran per Kategori (Juni 2024)')
plt.xticks(rotation=45)
plt.show()

#Agustus
kategori_pengeluaran_agustus = df[(df['year_month'] == '2024-08') & (df['type'] == 'EXPENSE')]
kategori_pengeluaran_agustus = kategori_pengeluaran_agustus.groupby('category')['amount'].mean().reset_index()
kategori_pengeluaran_agustus = kategori_pengeluaran_agustus.sort_values(by='amount', ascending=False)
tertinggi_agustus = kategori_pengeluaran_agustus.iloc[0]['category']
terendah_agustus = kategori_pengeluaran_agustus.iloc[-1]['category']

plt.figure(figsize=(10, 6))
plt.bar(kategori_pengeluaran_agustus['category'], kategori_pengeluaran_agustus['amount'])
plt.xticks(
    ticks=range(len(kategori_pengeluaran_agustus['category'])),
    labels=kategori_pengeluaran_agustus['category'],
    rotation=45
)
plt.title('Kategori Pengeluaran Tertinggi dan Terendah pada Bulan Agustus 2024')
plt.xlabel('Kategori Pengeluaran')
plt.ylabel('Rata-Rata Pengeluaran')
for index, row in kategori_pengeluaran_agustus.iterrows():
    plt.text(row['category'], row['amount'], f'{row["amount"]:.2f}', ha='center', va='bottom')
plt.show()

print(f"Tertinggi Agustus: Kategori {tertinggi_agustus}")
print(f"Terendah Agustus: Kategori {terendah_agustus}")

"""Kategori pengeluaran tertinggi di bulan Juni dan Agustus 2024 adalah kategori 0."""

from pandas._libs.tslibs.offsets import MonthBegin

# Apakah ada kategori pengeluaran yang tergolong melampaui batas normal di tiap bulannya?
df_expense = df[df['type'] == 'EXPENSE']

monthly_avg = df_expense.groupby(['year_month', 'category'])['amount'].mean().reset_index()
normal_avg = df_expense.groupby('category')['amount'].mean().reset_index().rename(columns={'amount': 'normal_avg_amount'})

compare_df = pd.merge(monthly_avg, normal_avg, on='category')

compare_df['Melampaui_Normal'] = compare_df['amount'] > compare_df['normal_avg_amount']

over_limit = compare_df[compare_df['Melampaui_Normal'] == True]
print(over_limit[['year_month', 'category', 'amount', 'normal_avg_amount']])

frekuensi = (
    compare_df[compare_df['Melampaui_Normal'] == True]
    .groupby('category')
    .size()
    .reset_index(name='Jumlah_Bulan_Di_Atas_Rata2')
)

print()
print("Frekuensi Kategori Melampaui Batas Normal:")
print(frekuensi)

"""Kategori yang paling sering berada di atas rata-rata pengeluaran adalah kategori 2"""

# Apa kategori pengeluaran yang sering dilakukan tiap bulannya?
frekuensi_bulanan = df.groupby('year_month')['category'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'No Category').reset_index()
print("Kategori Pengeluaran Paling Sering Dilakukan Tiap Bulannya:")
print(frekuensi_bulanan)

"""Kategori yang paling sering dikeluarkan untuk tiap bulannya adalah Transport

## **5. Feature Engenering**
"""

# one Hot Encoding
df_encoded = pd.get_dummies(df, columns=['category', 'account', 'type'])
df_encoded

# save data hasil encoded
df_encoded.to_csv('Financial_Transactions_encoded.csv', index=False)