# -*- coding: utf-8 -*-
"""Salinan dari Capstone_PembangunanModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlPabxPPXWMUFepCKBmnMzAPdY9YH_pU

## **1. Import Library**
"""

# Pastiin ini dijalanin dulu ya
#!pip install scikit-learn-extra
#!pip install "numpy<2"

# Library
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn_extra.cluster import KMedoids
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from yellowbrick.cluster import KElbowVisualizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report

from google.colab import drive
drive.mount('/content/drive')

"""## **2. Memuat Dataset**"""

# Load dataset hasil processing
url = "https://drive.google.com/uc?id=15xk83k4FAHyJAjnK4eqTpyn6N9dHtyxZ"
data = pd.read_csv(url)

#Hapus Fitur tidak terpakai
data = data.drop('year_month', axis=1)
data = data[data['type_TRANSFER'] == False].copy()

expense = data[data['type_EXPENSE'] == True].copy().reset_index(drop=True)
income  = data[data['type_INCOME']  == True].copy().reset_index(drop=True)

print(f"Total (tanpa transfer): {len(data)}")
print(f"Expense: {len(expense)} baris | Income: {len(income)} baris")
data.head()

"""## **3. Membangun Model**

1. Model Clustering (K-Medoids)
"""

# Elbow method untuk expense
k_range = range(2, 8)

scaler_exp = StandardScaler()
X_exp_scaled = scaler_exp.fit_transform(expense)

silhouette_scores_exp = []
for k in k_range:
    km = KMedoids(n_clusters=k, random_state=42)
    km.fit(X_exp_scaled)
    score = silhouette_score(X_exp_scaled, km.labels_)
    silhouette_scores_exp.append(score)

plt.figure(figsize=(8, 4))
plt.plot(k_range, silhouette_scores_exp, marker='o')
plt.title('Silhouette Score vs Jumlah Cluster - Expense')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('Silhouette Score')
plt.xticks(k_range)
plt.grid(True)
plt.show()

best_k_exp = k_range[silhouette_scores_exp.index(max(silhouette_scores_exp))]
print(f"Jumlah cluster terbaik (Expense): {best_k_exp}")

# Elbow method untuk income
scaler_inc = StandardScaler()
X_inc_scaled = scaler_inc.fit_transform(income)

silhouette_scores_inc = []
for k in k_range:
    km = KMedoids(n_clusters=k, random_state=42)
    km.fit(X_inc_scaled)
    score = silhouette_score(X_inc_scaled, km.labels_)
    silhouette_scores_inc.append(score)

plt.figure(figsize=(8, 4))
plt.plot(k_range, silhouette_scores_inc, marker='o')
plt.title('Silhouette Score vs Jumlah Cluster - Income')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('Silhouette Score')
plt.xticks(k_range)
plt.grid(True)
plt.show()

best_k_inc = k_range[silhouette_scores_inc.index(max(silhouette_scores_inc))]
print(f"Jumlah cluster terbaik (Income): {best_k_inc}")

# K-Medoids expense
model_kmedoids_exp = KMedoids(n_clusters=2, random_state=42)
model_kmedoids_exp.fit(X_exp_scaled)

labels_exp = model_kmedoids_exp.labels_
expense['Cluster'] = labels_exp

# Auto-relabel: cluster dengan amount rata-rata lebih tinggi = Anomali (1)
cluster_means_exp = expense.groupby('Cluster')['amount'].mean()
anomaly_cluster_exp = cluster_means_exp.idxmax()
expense['Label'] = (expense['Cluster'] == anomaly_cluster_exp).astype(int)

print("Statistik amount per cluster (Expense):")
print(expense.groupby('Cluster')['amount'].agg(['mean', 'min', 'max']).round(0))
print(f"\nCluster {anomaly_cluster_exp} → Anomali (amount lebih tinggi)")
print(f"\nDistribusi Label: {expense['Label'].value_counts().to_dict()}")
print(f"Silhouette Score: {silhouette_score(X_exp_scaled, labels_exp):.4f}")

joblib.dump(model_kmedoids_exp, 'model_kmedoids_expense.pkl')
joblib.dump(scaler_exp, 'scaler_expense.pkl')  # PENTING: simpan scaler juga

# K-Medoids income
model_kmedoids_inc = KMedoids(n_clusters=2, random_state=42)
model_kmedoids_inc.fit(X_inc_scaled)

labels_inc = model_kmedoids_inc.labels_
income['Cluster'] = labels_inc

cluster_means_inc = income.groupby('Cluster')['amount'].mean()
anomaly_cluster_inc = cluster_means_inc.idxmax()
income['Label'] = (income['Cluster'] == anomaly_cluster_inc).astype(int)

print("Statistik amount per cluster (Income):")
print(income.groupby('Cluster')['amount'].agg(['mean', 'min', 'max']).round(0))
print(f"\nCluster {anomaly_cluster_inc} → Anomali (amount lebih tinggi)")
print(f"\nDistribusi Label: {income['Label'].value_counts().to_dict()}")
print(f"Silhouette Score: {silhouette_score(X_inc_scaled, labels_inc):.4f}")

joblib.dump(model_kmedoids_inc, 'model_kmedoids_income.pkl')
joblib.dump(scaler_inc, 'scaler_income.pkl')

# Simpan Hasil Clustering
df_cluster_exp = expense.copy()
df_cluster_inc = income.copy()

df_cluster_exp.to_csv('Financial_Transactions_Cluster_Expense.csv', index=False)
df_cluster_inc.to_csv('Financial_Transactions_Cluster_Income.csv', index=False)

print("Expense cluster saved:", df_cluster_exp.shape)
print("Income cluster saved:", df_cluster_inc.shape)

"""2. Model Klasifikasi"""

#Train/Test Split Expense
X_exp = df_cluster_exp.drop(columns=['Cluster', 'Label'])
y_exp = df_cluster_exp['Label']

X_train_exp, X_test_exp, y_train_exp, y_test_exp = train_test_split(
    X_exp, y_exp, test_size=0.2, random_state=42, stratify=y_exp
)

print("=== EXPENSE ===")
print(f"Total: {len(X_exp)} | Train: {len(X_train_exp)} | Test: {len(X_test_exp)}")
print(f"Label train: {y_train_exp.value_counts().to_dict()}")

#Train/Test Split Income
X_inc = df_cluster_inc.drop(columns=['Cluster', 'Label'])
y_inc = df_cluster_inc['Label']

X_train_inc, X_test_inc, y_train_inc, y_test_inc = train_test_split(
    X_inc, y_inc, test_size=0.2, random_state=42, stratify=y_inc
)

print("=== INCOME ===")
print(f"Total: {len(X_inc)} | Train: {len(X_train_inc)} | Test: {len(X_test_inc)}")
print(f"Label train: {y_train_inc.value_counts().to_dict()}")

# Bangun Model Klasifikasi Expense
dt_expense = DecisionTreeClassifier(random_state=42)
dt_expense.fit(X_train_exp, y_train_exp)

print("Decision Tree Expense - Before Tuning:")
print(classification_report(y_test_exp, dt_expense.predict(X_test_exp)))

joblib.dump(dt_expense, 'model_dt_expense.pkl')

# Bangun Model Klasifikasi Income
dt_income = DecisionTreeClassifier(random_state=42)
dt_income.fit(X_train_inc, y_train_inc)

print("Decision Tree Income - Before Tuning:")
print(classification_report(y_test_inc, dt_income.predict(X_test_inc)))

joblib.dump(dt_income, 'model_dt_income.pkl')

"""## 4. Tuning Model"""

# Hyperparamter Tuning Expense
params = {
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy']
}

tuned_expense = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid=params,
    cv=5,
    scoring='accuracy'
)
tuned_expense.fit(X_train_exp, y_train_exp)

print("Best params (Expense):", tuned_expense.best_params_)
print("\nTuned Decision Tree Expense:")
print(classification_report(y_test_exp, tuned_expense.predict(X_test_exp)))

joblib.dump(tuned_expense.best_estimator_, 'model_dt_expense_tuned.pkl')

# Hyperparamter Tuning Income
tuned_income = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid=params,
    cv=5,
    scoring='accuracy'
)
tuned_income.fit(X_train_inc, y_train_inc)

print("Best params (Income):", tuned_income.best_params_)
print("\nTuned Decision Tree Income:")
print(classification_report(y_test_inc, tuned_income.predict(X_test_inc)))

joblib.dump(tuned_income.best_estimator_, 'model_dt_income_tuned.pkl')

"""## 5. Hasil Klasifikasi"""

# Expense
df_klasifikasi_exp = df_cluster_exp.copy()
df_klasifikasi_exp['Label_Pred'] = tuned_expense.predict(X_exp)
df_klasifikasi_exp['Status'] = df_klasifikasi_exp['Label_Pred'].map({0: 'Normal', 1: 'Anomali'})

# Income
df_klasifikasi_inc = df_cluster_inc.copy()
df_klasifikasi_inc['Label_Pred'] = tuned_income.predict(X_inc)
df_klasifikasi_inc['Status'] = df_klasifikasi_inc['Label_Pred'].map({0: 'Normal', 1: 'Anomali'})

df_klasifikasi_exp.to_csv('Financial_Transactions_Klasifikasi_Expense.csv', index=False)
df_klasifikasi_inc.to_csv('Financial_Transactions_Klasifikasi_Income.csv', index=False)

print("Expense - distribusi status:")
print(df_klasifikasi_exp['Status'].value_counts())
print("\nIncome - distribusi status:")
print(df_klasifikasi_inc['Status'].value_counts())

df_klasifikasi_exp.head()

df_cluster_inc.head()